Add build configuration system and paper image
- Add 'make paper' target to build a Paper image with plugins based on JRE
- Introduce dynamic .env and plugins.json configuration using Makefile
- Enable users to extend builds by managing their own directories in scratch/
- Implement copy_build_files macro for reproducible build management
- Add BUILDKIT_PROGRESS and DOCKER_BUILDKIT as configurable make vars

diff --git a/dockerfiles/Dockerfile.paper b/dockerfiles/Dockerfile.paper
--- a/dockerfiles/Dockerfile.paper
+++ b/dockerfiles/Dockerfile.paper
@@ -1,54 +1,51 @@
-# Build from OpenJDK image
-FROM "${JDK_IMAGE:-localhost/minecraft-jdk}":"${JDK_TAG:-latest}" as build
+FROM "${JRE_IMAGE:-localhost/minecraft-jre}":"${JRE_TAG:-latest}"
 
-# Minecraft version
+# Minecraft version to download
 ARG VERSION=latest
-
-# Defaults to building Spigot over CraftBukkit
-ARG SPIGOT=true
 
 # Plugins prefix
 ARG PREFIX="PLUGIN_"
 
-# SpigotMC BuildTools URL
-ARG BASE_URL="https://hub.spigotmc.org/jenkins/job/BuildTools/"
-ARG ARTIFACT_PATH="lastSuccessfulBuild/artifact/target/BuildTools.jar"
+# PaperMC base URL
+ARG BASE_URL="https://api.papermc.io/v2/projects/paper/versions/${VERSION}"
 
-# Build in common container location
-WORKDIR /build
+# Download files
+USER root
+WORKDIR /app
 
-# Download and build Spigot using BuildTools
+# Download and verify sha256sum for PaperMC server.jar
 RUN set -eux && \
-# Grab latest version if not specified
+  # Grab latest version if not specified
   if [ "$VERSION" = "latest" ]; then \
     VERSION="$( \
-      curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json \
-        | jq -r '.latest.release' \
+      curl -s https://api.papermc.io/v2/projects/paper | \
+        jq -r '.versions[-1]' \
     )"; \
   fi && \
-  # Download BuildTools.jar
-  curl -s -o BuildTools.jar "${BASE_URL}${ARTIFACT_PATH}" && \
-  # Build Craftbukkit if SPIGOT is false
-  case "$SPIGOT" in \
-    true) \
-      BUILD_TYPE='SPIGOT' ;; \
-    false) \
-      BUILD_TYPE='CRAFTBUKKIT' ;; \
-    *) \
-      echo "ERROR: Invalid value for SPIGOT. Set to 'true' or 'false'"; \
-      exit 1 ;; \
-  esac && \
-  # Run BuildTools to build specified version
-  java -jar BuildTools.jar --rev "$VERSION" --compile "$BUILD_TYPE" && \
-  ln -s \
-    "$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')-${VERSION}.jar" \
-    "server.jar"
+  # Get latest build for the specified version
+  BUILD="$( \
+    curl -s "$BASE_URL" \
+      | jq -r '.builds[-1]' \
+  )" && \
+  URL="${BASE_URL}/builds/${BUILD}/downloads/paper-${VERSION}-${BUILD}.jar" && \
+  curl -s -o /tmp/server.jar "$URL" && \
+  # Get SHA256 hash of server.jar and compare
+  SHA256="$(sha256sum /tmp/server.jar | awk '{print $1}')" && \
+  EXPECTED="$( \
+    curl -s "$BASE_URL/builds/$BUILD" \
+      | jq -r '.downloads.application.sha256' \
+  )" && \
+  if [ ! "$SHA256" = "$EXPECTED" ]; then \
+    echo "[ERROR] SHA256=\"$SHA256\" expected \"$EXPECTED\""; \
+    exit 1; \
+  fi && \
+  mv /tmp/server.jar /app/server.jar
 
 # Move into a directory just for storing plugins
-WORKDIR /plugins
+WORKDIR /app/plugins
 
 # Copy in plugins
-COPY ../plugins.json /plugins/
+COPY ../plugins.json /app/plugins
 
 # Download defined plugins
 RUN set -eux && \
@@ -92,29 +89,16 @@ RUN set -eux && \
     esac && \
     mv "$tmp_file" "${name}-${version}.jar"; \
   done && \
-  rm -rf "$tmp_downloads"
-
-# Use OpenJRE image for runtime
-FROM "${JRE_IMAGE:-localhost/minecraft-jre}":"${JRE_TAG:-latest}" as runtime
-
-# Run as Minecraft user
-USER minecraft
-WORKDIR /app
-
-# Copy the built bukkit jar from the build stage
-COPY --from=build /build/server.jar /app/server.jar
-
-# Copy in plugins
-COPY --from=build /plugins/ /app/plugins/
+  rm -rf "$tmp_downloads" && \
+  chown minecraft:minecraft /app/plugins/
 
 # Generate initial settings
+USER minecraft
+WORKDIR /app
 RUN java -jar server.jar --initSettings --nogui
 
 # Back to root to copy the entrypoint in
 USER root
-WORKDIR /app
-
-# Copy in entrypoint script
 COPY ../entrypoint.sh /usr/local/bin/entrypoint.sh
 RUN chmod +x /usr/local/bin/entrypoint.sh
 
